### ISSUE TITLE
fix: 트리거 변경

### ISSUE THREAD

**Issue by thguss** [HisTour/HisTour-Spring#31]
### 기능 설명

- 릴리즈 변화가 트리거가 되어 CD 스크립트가 실행되도록 한다.

### 추가 정보

```
on:
  release:
    types:
      - published
```
